### PR TITLE
rsvp envelope proto

### PR DESCRIPTION
**Pull request by achiu8**
Quick proto:

screen shot 2015-08-05 at 12 24 25 am

### CODE REVIEW

**Comment by kprakobkit** [comment]
damnnnnnnn son

**Comment by kprakobkit** [comment]
looks really good. are the forms suppose to be fillable, or just static for this prototype?

**Comment by kprakobkit** [comment]
nvm - i can fill-in parts of the form that are above the red marker - this is at 75% zoom, at 100% I can't complete anything . Can you look into it? otherwise it looks really freakin' good.
screen shot 2015-08-05 at 9 04 19 am

**Comment by achiu8** [comment]
Yeah I'll mess around with the sizing and functionality. Just wanted to get this up so we could see how it looks on the site.

**Comment by kprakobkit** [comment]
cool - should i just merge this or wait for your changes?

**Comment by achiu8** [comment]
Probably fine to merge so we can see on staging.

**Pull request merged**
